# Generated by Django 4.2.4 on 2023-08-15 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='books_authored', to=settings.AUTH_USER_MODEL),
        ),
    ]
